#!/bin/bash -e

if [ ! -h gopath/src/github.com/coreos/locksmith ]; then
	mkdir -p gopath/src/github.com/coreos/
	ln -s ../../../.. gopath/src/github.com/coreos/locksmith
fi

export GOBIN=${PWD}/bin
export GOPATH=${PWD}/gopath
export GO15VENDOREXPERIMENT=1

eval $(go env)

go install -ldflags "$GOLDFLAGS" github.com/coreos/locksmith/locksmithctl
