#!/bin/bash -e

PKGS=$(go list ./... | grep -v vendor)
FMT_DIRS=$(ls -d */ | grep -v vendor)
LINTABLE=$(go list ./... | grep -v vendor)

echo "Running tests..."
go test $PKGS -cover

echo "Running vet..."
go vet $PKGS

echo "Running gofmt..."
fmtRes=$(gofmt -l $FMT_DIRS)
if [[ -n "${fmtRes}" ]]; then
	echo -e "gofmt checking failed:\n${fmtRes}"
	exit 2
fi

echo "Running golint..."
echo $LINTABLE | xargs -n 1 golint || true

echo "Success"
